### ISSUE TITLE
ansible-vault create secrets.yml

### ISSUE THREAD

**Issue by boschpeter** [boschpeter/ansible#2]
https://www.digitalocean.com/community/tutorials/how-to-use-vault-to-protect-sensitive-ansible-data-on-ubuntu-16-04

````
# To run this, name this file vm_touch.yml and run the following in the same directory
# ansible-playbook  -l dingofarm_workers vm_clone_socialcoin-api.yml  
---
  - name: checkout application
    hosts: all
    vars_files:
       - secrets.yml
    vars:
       - destdir: /home/boscp08/Projects/scratch/virtual-insanity
       - 
    tasks:

        - name: Download the NodeJS code from the GitRepo
         become: yes
         git:
            repo: 'https://{{gituser}}:{{gitpass}}@github.com/AKSarav/SampleNodeApp.git'
            dest: "{{ destdir }}"
````
