### ISSUE TITLE
git clone Host key verification failed.: Could not read from remote repository.

### ISSUE THREAD

**Issue by boschpeter** [boschpeter/ansible#7]
````
fatal: [ubuntuvbx]: FAILED! => {"changed": false, "cmd": "/usr/bin/git clone --origin origin '' /home/boscp08/Projects/scratch/virtual-insanity", "msg": "Cloning into '/home/boscp08/Projects/scratch/virtual-insanity'...\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.", "rc": 128, "stderr": "Cloning into '/home/boscp08/Projects/scratch/virtual-insanity'...\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n", "stderr_lines": ["Cloning into '/home/boscp08/Projects/scratch/virtual-insanity'...", "Host key verification failed.", "fatal: Could not read from remote repository.", "", "Please make sure you have the correct access rights", "and the repository exists."], "stdout": "", "stdout_lines": []}
fatal: [ubuntuvbx2]: FAILED! => {"changed": false, "cmd": "/usr/bin/git clone --origin origin '' /home/boscp08/Projects/scratch/virtual-insanity", "msg": "Cloning into '/home/boscp08/Projects/scratch/virtual-insanity'...\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.", "rc": 128, "stderr": "Cloning into '/home/boscp08/Projects/scratch/virtual-insanity'...\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n", "stderr_lines": ["Cloning into '/home/boscp08/Projects/scratch/virtual-insanity'...", "Host key verification failed.", "fatal: Could not read from remote repository.", "", "Please make sure you have the correct access rights", "and the repository exists."], "stdout": "", "stdout_lines": []}
````

**Comment by boschpeter** [comment]
````

mkdir -p ~/.ssh
ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
ssh-keygen -t rsa -C "user.email"
open the public key with this command $ cat ~/.ssh/id_rsa.pub and copy it.
Add the id_rsa.pub key to SSH keys list on your GitHub profile.

````

**Comment by boschpeter** [comment]
````
---
- hosts: localhost
  gather_facts: no
  vars:
    git_ssh_public_key: "Your public ssh key"
    git_ssh_key: |
              -----BEGIN RSA PRIVATE KEY-----
              .... actual key here ....
              -----END RSA PRIVATE KEY-----
  tasks:
  - name: Copy SSH public key file
    copy: 
      content: "{{ git_ssh_public_key }}"
      dest: /root/.ssh/id_rsa.pub
      mode: 0644

  - name: Copy SSH private key file
    copy: 
      content: "{{ git_ssh_key }}"
      #src: id_rsa
      dest: /root/.ssh/id_rsa
      mode: 0600

  - name: Get new source from GIT
    git: 
      repo: "git@gitlab.com:user/repo.git"
      dest: "/var/www/"
      depth: 1
      accept_hostkey: yes
      clone: yes
````
