### ISSUE TITLE
nodejs 10_18_1

### ISSUE THREAD

**Issue by boschpeter** [boschpeter/ansible#9]
ansible-playbook site.yml -i hosts -k -K
https://github.com/William-Yeh/ansible-nodejs

````
---
- name: Ensure apt-transport-https is installed.
  apt: name=apt-transport-https state=present

- name: Add Nodesource apt key.
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: Add NodeSource repositories for Node.js.
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
  register: node_repo

- name: Update apt cache if repo was added.
  apt: update_cache=yes
  when: node_repo.changed
  tags: ['skip_ansible_lint']

- name: Ensure Node.js and npm are installed.
  apt:
    name: "nodejs={{ nodejs_version|regex_replace('x', '') }}*"
    state: present

````
